operator:
  enabled: true
  fullnameOverride: otel-operator
  additionalLabels:
    app: otel-operator
  replicaCount: 1
  manager:
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: 0.124.0
    collectorImage:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib 
      tag: 0.129.1
    autoInstrumentationImage:
      java:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java
        tag: 1.33.6
      nodejs:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs
        tag: 0.58.0
      go: 
        repository: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go
        tag: v0.19.0-alpha
      python:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
        tag: 0.53b1
      dotnet:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet
        tag: 1.2.0
      apacheHttpd:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd
        tag: 1.0.4
    # serviceMonitor:
    #   enabled: true
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
      recreate: false
      certPeriodDays: 3650
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: operator
                app: otel-operator
            topologyKey: kubernetes.io/hostname