apiVersion: v2
name: grafana
description: A Helm chart to deploy Grafana
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    alias: grafana
    version: 8.15.0
    repository: https://grafana.github.io/helm-charts
