apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-apps-critical-rules
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: KubePodRestarting
      annotations:
        description: Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} ({{`{{ $labels.container }}`}}) is restarting {{`{{ printf "%.2f" $value }}`}} times / 5 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        summary: Pod is Restarting.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr:  rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~".*"}[5m]) * 60 * 5 >= 5
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubePodNotReady
      annotations:
        description: Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} has been in a non-ready state for longer than 15 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodnotready
        summary: Pod has been in a non-ready state for more than 20 minutes.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        sum by (namespace, pod, env) (
          max by(namespace, pod,env) (
            kube_pod_status_phase{job="kube-state-metrics", namespace=~".*", phase=~"Pending|Unknown"}
          ) * on(namespace, pod) group_left(owner_kind, env) topk by(namespace, pod) (
            1, max by(namespace, pod, owner_kind,env) (kube_pod_owner{owner_kind!="Job"})
          )
        ) > 0
      for: 20m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubeDeploymentGenerationMismatch 
      annotations:
        description: Deployment generation for {{`{{ $labels.namespace }}`}}/{{`{{ $labels.deployment }}`}} does not match, this indicates that the Deployment has failed but has not been rolled back.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentgenerationmismatch
        summary: Deployment generation mismatch due to possible roll-back
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        kube_deployment_status_observed_generation{job="kube-state-metrics", namespace=~".*"}
          !=
        kube_deployment_metadata_generation{job="kube-state-metrics", namespace=~".*"}
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubeDeploymentReplicasMismatch 
      annotations:
        description: Deployment {{`{{ $labels.namespace }}`}}/{{`{{ $labels.deployment }}`}} has not matched the expected number of replicas for longer than 15 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedeploymentreplicasmismatch
        summary: Deployment has not matched the expected number of replicas.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        (
          kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~".*"}
            !=
          kube_deployment_status_replicas_available{job="kube-state-metrics", namespace=~".*"}
        ) and (
          changes(kube_deployment_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        

    - alert: KubeStatefulSetReplicasMismatch 
      annotations:
        description: StatefulSet {{`{{ $labels.namespace }}`}}/{{`{{ $labels.statefulset }}`}} has not matched the expected number of replicas for longer than 15 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetreplicasmismatch
        summary: Deployment has not matched the expected number of replicas.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        (
          kube_statefulset_status_replicas_ready{job="kube-state-metrics", namespace=~".*"}
            !=
          kube_statefulset_status_replicas{job="kube-state-metrics", namespace=~".*"}
        ) and (
          changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes

    - alert: KubeStatefulSetGenerationMismatch 
      annotations:
        description: StatefulSet generation for {{`{{ $labels.namespace }}`}}/{{`{{ $labels.statefulset }}`}} does not match, this indicates that the StatefulSet has failed but has not been rolled back.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetgenerationmismatch
        summary: StatefulSet generation mismatch due to possible roll-back
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        kube_statefulset_status_observed_generation{job="kube-state-metrics", namespace=~".*"}
          !=
        kube_statefulset_metadata_generation{job="kube-state-metrics", namespace=~".*"}
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes

    - alert: KubeStatefulSetUpdateNotRolledOut 
      annotations:
        description: StatefulSet {{`{{ $labels.namespace }}`}}/{{`{{ $labels.statefulset }}`}} update has not been rolled out.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatefulsetupdatenotrolledout
        summary: StatefulSet update has not been rolled out.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        (
          max without (revision) (
            kube_statefulset_status_current_revision{job="kube-state-metrics", namespace=~".*"}
              unless
            kube_statefulset_status_update_revision{job="kube-state-metrics", namespace=~".*"}
          )
            *
          (
            kube_statefulset_replicas{job="kube-state-metrics", namespace=~".*"}
              !=
            kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}
          )
        )  and (
          changes(kube_statefulset_status_replicas_updated{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes

    - alert: KubeDaemonSetRolloutStuck 
      annotations:
        description: DaemonSet {{`{{ $labels.namespace }}`}}/{{`{{ $labels.daemonset }}`}} has not finished or progressed for at least 15 minutes.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
        summary: DaemonSet rollout is stuck.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        (
          (
            kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          ) or (
            kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            0
          ) or (
            kube_daemonset_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          ) or (
            kube_daemonset_status_number_available{job="kube-state-metrics", namespace=~".*"}
            !=
            kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          )
        ) and (
          changes(kube_daemonset_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}[5m])
            ==
          0
        )
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes

    - alert: KubeContainerWaiting 
      annotations:
        description: Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} container {{`{{ $labels.container}}`}} has been in waiting state for longer than 1 hour.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontainerwaiting
        summary: Pod container waiting longer than 1 hour
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: sum by (namespace, pod, container,env) (kube_pod_container_status_waiting_reason{job="kube-state-metrics", namespace=~".*"}) > 0
      for: 1h
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes

    - alert: KubeDaemonSetNotScheduled 
      annotations:
        description: '{{`{{ $value }}`}} Pods of DaemonSet {{`{{ $labels.namespace }}`}}/{{`{{ $labels.daemonset }}`}} are not scheduled.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetnotscheduled
        summary: DaemonSet pods are not scheduled.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"}
          -
        kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"} > 0
      for: 10m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubeDaemonSetMisScheduled 
      annotations:
        description: '{{`{{ $value }}`}} Pods of DaemonSet {{`{{ $labels.namespace }}`}}/{{`{{ $labels.daemonset }}`}} are running where they are not supposed to run.'
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetmisscheduled
        summary: DaemonSet pods are misscheduled.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"} > 0
      for: 30m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubePodCrashLoopBackOff
      expr: kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} > 0    
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} is in CrashLoopBackOff state.'
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url:  https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-KubePodCrashLooping
        summary: A pod is repeatedly crashing and entering CrashLoopBackOff state.
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: PodHighCpuUsageCritical
      annotations:
        description: "Pod {{`{{ $labels.pod }}`}} is using more than 85% of CPU."
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        summary: "Critical: Pod CPU usage is very high."
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{namespace=~".*", container!="POD", container!="", pod!=""}[3m])) by (namespace, pod)
        ) / (
          sum(kube_pod_container_resource_limits{namespace=~".*", pod=~".*", resource="cpu"}) by (namespace, pod)
        ) * 100 > 85
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
  
    - alert: Http500ErrorOccurred
      annotations:
        description: '500 HTTP errors occurred in the {{`{{$labels.service_name}}`}} in the alpha-prod at route {{`{{$labels.http_route}}`}}. Error count: {{`{{$value}}`}}.'
        summary: '500 HTTP error occurred'
        dashboard_url: 'https://grafana-internal.stablemoney.in/d/fe99z7j1ev2f4f/500error?orgId=1&var-DataSource=be7a88twp69s0d'
      expr: |
        sum by (http_route, service_name) (
          increase(traces_span_metrics_duration_milliseconds_count{http_status_code=~"^5.*"}[5m])
        ) > 0
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
   
  
   
