
apiVersion: 1
datasources:
  - name: "VictoriaMetrics"
    type: prometheus
    uid: victoriametrics
    url: http://vmselect-vm.monitoring.svc.cluster.local.:8481/select/0/prometheus 
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      exemplars: true
