apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kube-node-critical-rules
  namespace: monitoring
spec:
  groups:
  - name: kube-node-critical-rules
    rules:
    - alert: HostMemoryUnderMemoryPressure 
      expr: rate(node_vmstat_pgmajfault[1m]) > 1000
      for: 2m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host memory under memory pressure (instance {{`{{ $labels.instance }}`}})
        description: "The node is under heavy memory pressure. High rate of major page faults\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        dashboard_url: https://grafana.k8s.opstree.dev/explore
    - alert: HostUnusualNetworkThroughputIn 
      expr: sum by (instance) (rate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 1000
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual network throughput in (instance {{`{{ $labels.instance }}`}})
        description: "Host network interfaces are probably receiving too much data (> 150 MB/s)\n  VALUE = {{`{{ $value }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: HostUnusualNetworkThroughputOut 
      expr: sum by (instance) (rate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 400
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual network throughput out (instance {{`{{ $labels.instance }}`}})
        description: "Host network interfaces are probably sending too much data (> 150 MB/s)\n  VALUE = {{`{{ $value }}`}}"
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
        dashboard_url: https://grafana.k8s.opstree.dev/explore
    - alert: HostUnusualDiskReadRate 
      expr: sum by (instance) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 400
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual disk read rate (instance {{`{{ $labels.instance }}`}})
        description: "Disk is probably reading too much data (> 400 MB/s)\n  VALUE = {{`{{ $value }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: HostUnusualDiskWriteRate 
      expr: sum by (instance) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 400
      for: 15m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual disk write rate (instance {{`{{ $labels.instance }}`}})
        description: "Disk is probably writing too much data (> 400 MB/s)\n  VALUE = {{`{{ $value }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.mdd
    - alert: HostUnusualDiskReadLatency 
      expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0
      for: 2m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual disk read latency (instance {{`{{ $labels.instance }}`}})
        description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: HostUnusualDiskWriteLatency 
      expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 1
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host unusual disk write latency (instance {{`{{ $labels.instance }}`}})
        description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: HostHighCpuLoad 
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 95
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host high CPU load (instance {{`{{ $labels.instance }}`}})
        description: "CPU load is > 95%\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: HostSwapIsFillingUp 
      expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 90
      for: 2m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host swap is filling up (instance {{`{{ $labels.instance }}`}})
        description: "Swap is filling up (>80%)\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
    - alert: KubePersistentVolumeFillingUp
      annotations:
        description: Based on recent sampling, the PersistentVolume claimed by {{`{{ $labels.persistentvolumeclaim }}`}} in Namespace {{`{{ $labels.namespace }}`}} is expected to fill up within four days. Currently {{`{{ $value | humanizePercentage }}`}} is available.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumefillingup
        summary: PersistentVolume is filling up.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: |-
        (
          kubelet_volume_stats_available_bytes{job="kubelet", namespace=~".*", metrics_path="/metrics"}
            /
          kubelet_volume_stats_capacity_bytes{job="kubelet", namespace=~".*", metrics_path="/metrics"}
        ) < 0.15
        and
        predict_linear(kubelet_volume_stats_available_bytes{job="kubelet", namespace=~".*", metrics_path="/metrics"}[6h], 4 * 24 * 3600) < 0
      for: 1h
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: KubePersistentVolumeErrors 
      annotations:
        description: The persistent volume {{`{{ $labels.persistentvolume }}`}} has status {{`{{ $labels.phase }}`}}.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeerrors
        summary: PersistentVolume is having issues with provisioning.
        dashboard_url: https://grafana.k8s.opstree.dev/explore
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0
      for: 5m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: NodeFilesystemAlmostOutOfSpace 
      annotations:
        summary: Node filesystem  out of space. Filesystem has less than 10% space left.
        description: Filesystem on {{`{{ $labels.device }}`}} at {{`{{ $labels.instance }}`}} has only {{`{{ printf "%.2f" $value }}`}}% available space left.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutofspace
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 10
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: NodeFilesystemAlmostOutOfFiles 
      annotations:
        description: Filesystem on {{`{{ $labels.device }}`}} at {{`{{ $labels.instance }}`}} has only {{`{{ printf "%.2f" $value }}`}}% available inodes left.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutoffiles
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        summary: Filesystem has less than 10% inodes left.
      expr: |-
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 10
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
    - alert: HostOomKillDetected 
      expr: increase(node_vmstat_oom_kill[1m]) > 10
      for: 0m
      labels:
        severity: critical
        channel: slack
        team: devops
        alert: kubernetes
      annotations:
        summary: Host OOM kill detected (instance {{`{{ $labels.instance }}`}}) 5 times in last 1 minute
        description: "OOM kill detected\n  VALUE = {{`{{ $value }}`}}\n  LABELS = {{`{{ $labels }}`}}"
        dashboard_url: https://grafana.k8s.opstree.dev/explore
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md
