operator:
  enabled: true
  fullnameOverride: otel
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-contrib
      tag: v0.124.0
  admissionWebhooks:
    certManager:
      enabled: false
    autoGenerateCert:
      enabled: true
