apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.Namespace }} 
  labels:
    app.kubernetes.io/name: {{ include "grafana-folders.name" . }}
    helm.sh/chart: {{ include "grafana-folders.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
 
  folders.yaml: |
{{ .Values.foldersConfig | toYaml | indent 4 }}
