apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-folder-provider
  namespace: {{ .Release.Namespace }}
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'folders'
        type: file
        options:
          path: /etc/grafana/provisioning/folders

