annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - Synced dashboards and rules
    - Support wildcard in ingress hostname. See [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/2134).
    - Do not replace VMCluster URL with VMAuth one, when it's enabled, for VMAlert, Grafana datasources and VMAgent write endpoint. Consider using [`vmcluster.requestsLoadBalancer`](https://docs.victoriametrics.com/operator/resources/vmcluster/#requests-load-balancing) for balancing read and write requests to VMCluster. See [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/2136).
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v1.115.0
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
- condition: victoria-metrics-operator.enabled
  name: victoria-metrics-operator
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.45.*
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.31.*
- condition: prometheus-node-exporter.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.45.*
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.11.*
description: Kubernetes monitoring on VictoriaMetrics stack. Includes VictoriaMetrics
  Operator, Grafana dashboards, ServiceScrapes and VMRules
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-k8s-stack
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.44.0
